Issue92 cleanup example
akvelon/flutter-code-editor pull request #129
Opened 2022-12-22 18:42 UTC by yescorp

2022-12-22 18:45 UTC, yescorp commented on example/lib/03.control/code_editor.dart
> +      _codeController = codeControllers[_language]!;
It doesn't reflect the UI if I only change language property in the codeController, like:
`_codeController.language = builtinLanguages[value];`

Still looking for a better way to do it.

2022-12-23 07:33 UTC, alexeyinkin requested changes

2022-12-23 07:33 UTC, alexeyinkin commented on example/lib/03.change_language_theme/constants/constants.dart
> +
Move `../`

2022-12-23 07:33 UTC, alexeyinkin commented on example/lib/03.change_language_theme/constants/constants.dart
> +  'dart': dart,
Sort.

2022-12-23 07:33 UTC, alexeyinkin commented on example/lib/03.change_language_theme/home_screen.dart
> +
```dart
const _defaultLanguage = 'java';
const _defaultTheme = 'monokai-sublime';
```

2022-12-23 07:33 UTC, alexeyinkin commented on example/lib/03.change_language_theme/constants/constants.dart
> +  'dart',
Sort.

2022-12-23 07:33 UTC, alexeyinkin commented on example/lib/03.change_language_theme/constants/constants.dart
> +  'atom-one-dark',
Sort.

2022-12-23 07:33 UTC, alexeyinkin commented on example/lib/03.change_language_theme/home_screen.dart
> +              values: languageList),
Trailing comma.

2022-12-23 07:33 UTC, alexeyinkin commented on example/lib/03.change_language_theme/home_screen.dart
> +          // Language Selector
Delete.

2022-12-23 07:33 UTC, alexeyinkin commented on example/lib/03.change_language_theme/home_screen.dart
> +          // Theme selector
Delete.

2022-12-23 07:33 UTC, alexeyinkin commented on example/lib/03.change_language_theme/home_screen.dart
> +          ),
To a single line.

2022-12-23 07:33 UTC, alexeyinkin commented on example/lib/03.change_language_theme/widgets/dropdown_selector.dart
> +}
https://medium.com/@alexey.inkin/how-to-force-newline-at-end-of-files-and-why-you-should-do-it-fdf76d1d090e

2022-12-23 08:39 UTC, alexeyinkin requested changes

2022-12-23 08:39 UTC, alexeyinkin commented on example/lib/03.change_language_theme/constants.dart
> +  'vs',
Swap.

2022-12-23 12:20 UTC, alexeyinkin requested changes

2022-12-23 12:20 UTC, alexeyinkin commented on example/lib/03.change_language_theme/home_screen.dart
>      super.dispose();
`super.dispose();` should be called last.

2022-12-26 10:10 UTC, alexeyinkin approved these changes

2022-12-26 10:10 UTC, merged