Foldable block matcher fix
akvelon/flutter-code-editor pull request #177
Opened 2023-02-04 11:42 UTC by yescorp

2023-02-06 14:00 UTC, alexeyinkin requested changes

2023-02-06 14:00 UTC, alexeyinkin commented on test/src/code_field/code_controller_folding_editing_test.dart
> +            controller.value = controller.value.replacedSelection('\na');
```suggestion
            controller.value = controller.value.replacedSelection('\n');
```
It a timer issue arises, debug it.

2023-02-07 09:05 UTC, yescorp commented on lib/src/gutter/gutter.dart
> +      if (code.lines.length <= block.lastLine) {
This is an `early return condition` 
If we change the positions the condition should be the same I think.

2023-02-08 14:06 UTC, alexeyinkin requested changes

2023-02-08 14:06 UTC, alexeyinkin commented on test/src/code_field/code_controller_folding_editing_test.dart
> +            const example = 'package example;\nimport java.util.date;\n';
```suggestion
            const example = 'package example;\nimport java.util.Date;\n';
```

2023-02-08 14:06 UTC, alexeyinkin commented on test/src/code_field/code_controller_folding_editing_test.dart
> +          testWidgets('Add new import after folded imports block', (wt) async {
```suggestion
          testWidgets('Adding an import after folded imports -> Unfold', (wt) async {
```

2023-02-08 14:06 UTC, alexeyinkin commented on test/src/code_field/code_controller_folding_editing_test.dart
> +              'Add anything but imports line after folded imports block',
```suggestion
              'Adding non-import after folded imports -> Does not unfold',
```

2023-02-08 14:06 UTC, alexeyinkin commented on test/src/code_field/code_controller_folding_editing_test.dart
> +            await wt.moveCursor(-1); // reset timer
```suggestion
            await wt.moveCursor(-1); // Reset timer.
```

2023-02-10 09:18 UTC, alexeyinkin requested changes

2023-02-10 09:18 UTC, alexeyinkin commented on test/src/code_field/code_controller_folding_editing_test.dart
> +          testWidgets('1. Doesn\' unfold the block', (wt) async {
```suggestion
          testWidgets('Does not unfold the block', (wt) async {
```

2023-02-10 09:52 UTC, alexeyinkin approved these changes

2023-02-10 09:52 UTC, merged