Issue192 paired symbols, issue199 yaml support
akvelon/flutter-code-editor pull request #231
Opened 2023-04-26 11:14 UTC by Malarg

resolves #192
resolves #199

2023-05-11 06:40 UTC, alexeyinkin requested changes

2023-05-11 06:40 UTC, alexeyinkin commented on lib/src/code_modifiers/paired_symbols.dart
> +class PairedSymbolsCodeModifier extends CodeModifier {
```suggestion
class InsertionCodeModifier extends CodeModifier {
```

2023-05-16 06:26 UTC, Malarg commented on lib/src/code_field/code_controller.dart
> +      PairedSymbolsCodeModifier(openChar: '\'', closeString: '\''),
done

2023-05-16 06:26 UTC, Malarg commented on lib/src/code_modifiers/paired_symbols.dart
> +class PairedSymbolsCodeModifier extends CodeModifier {
done

2023-05-17 06:39 UTC, alexeyinkin commented on test/src/code_modifiers/insertion_test.dart
We need two tests:
1. A unit test to `InsertionCodeModifer` with `1` and `23` strings.
2. A test on `CodeController` that if created with the default parameters it handles all 6 pairs of characters.

2023-05-22 07:29 UTC, Malarg commented on test/src/code_modifiers/insertion_test.dart
done

2023-06-06 06:29 UTC, alexeyinkin requested changes

2023-06-06 06:29 UTC, alexeyinkin commented on lib/src/wip/autocomplete/popup_controller.dart
> +    itemScrollController = ItemScrollController();
What is the desired effect of this? Scroll to the top? If so, can you manually scroll to the top?

Replacing the controller has the drawbacks:
- Need to dispose the old one.
- Need to make sure the disposed one will not show in a widget and break it.

2023-06-06 06:29 UTC, alexeyinkin commented on test/src/code_modifiers/insertion_test.dart
> +  test('inserts at the start of string correctly', () {
`group('InsertionCodeModifier', ...`

2023-06-06 06:29 UTC, alexeyinkin commented on test/src/code_modifiers/insertion_test.dart
> +    const modifier = InsertionCodeModifier(openChar: '1', closeString: '23');
Make global?

2023-06-06 06:29 UTC, alexeyinkin commented on test/src/code_modifiers/insertion_test.dart
> +    const editorParams = EditorParams();
Make global?

2025-03-07 15:23 UTC, DzmitrySalauyeuAkvelon commented
Squashed commits, rebased on the current codebase branch and made [MR #290](https://github.com/akvelon/flutter-code-editor/pull/290) based on that code.
Would close this MR when this new MR would be closed

2026-01-01 06:55 UTC, closed without merging

2026-01-01 06:55 UTC, nausharipov commented
closed because https://github.com/akvelon/flutter-code-editor/pull/290 is merged